### ISSUE TITLE
AutoUpdate not working

### ISSUE THREAD

**Issue by mattseemon** [mattseemon/Vault#4]
* AutoUpdate download the latest version
* Copy of updated version not working and times out.

**Comment by mattseemon** [comment]
Issue resolved with [5595040](https://github.com/mattseemon/Vault/commit/5595040e3ea3159ea0676dbffb9f82f39097f7a5)

**Comment by mattseemon** [comment]
AutoUpdate failing with the following error.
`
2021-04-05 08:01:44.110 (0.4.61-alpha) [ERR] [UpdateManager] Error updating application path. Retrying
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Seemon.Vault.Helpers.UpdateManager.Update(String destination) in XXX\Vault\src\Helpers\UpdateManager.cs:line 198
`
